version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    environment:
      MONGO_URI: mongodb://db/appdb
      NODE_ENV: 'development'
      STORE_PORT: ${STORE_PORT}
      AUTH_PORT: ${AUTH_PORT}
      APP_PORT: ${APP_PORT}
      PORT: ${PORT}
      APP_URL: ${APP_URL}
      AUTH_HASH_SALT_TIMES: ${AUTH_HASH_SALT_TIMES}
      AUTH_SECRET_VALUE: ${AUTH_SECRET_VALUE}
      AUTH_URL: ${AUTH_URL}
      STORE_URL: ${STORE_URL}
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
